### PR TITLE
Changed the url to CF variables

### PR DESCRIPTION
**Pull request by mortenwh**
This should solve #35

### CODE REVIEW

**Comment by akorosov** [comment]
Hmm, strange it fails only for Python 2.7...

**Comment by mortenwh** [comment]
I can try to look at p2.7 error but why do you want to support that version of python when it has already passed "end of life"?

**Comment by mortenwh** [comment]
@akorosov - What is the status here? Can it be merged? I have another PR coming up ;)

**Review by akorosov — APPROVED** [review]
Looks great! Thank you, @mortenwh !

**Pull request merged**
